# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: electrum.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='electrum.proto',
  package='electrum',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x65lectrum.proto\x12\x08\x65lectrum\"1\n\x0eGetMerkleProof\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\"?\n\x0bMerkleProof\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\x0e\n\x06merkle\x18\x02 \x03(\x0c\x12\x10\n\x08position\x18\x03 \x01(\x05\x62\x06proto3'
)




_GETMERKLEPROOF = _descriptor.Descriptor(
  name='GetMerkleProof',
  full_name='electrum.GetMerkleProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='electrum.GetMerkleProof.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='electrum.GetMerkleProof.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=77,
)


_MERKLEPROOF = _descriptor.Descriptor(
  name='MerkleProof',
  full_name='electrum.MerkleProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='electrum.MerkleProof.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='electrum.MerkleProof.merkle', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='electrum.MerkleProof.position', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['GetMerkleProof'] = _GETMERKLEPROOF
DESCRIPTOR.message_types_by_name['MerkleProof'] = _MERKLEPROOF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMerkleProof = _reflection.GeneratedProtocolMessageType('GetMerkleProof', (_message.Message,), {
  'DESCRIPTOR' : _GETMERKLEPROOF,
  '__module__' : 'electrum_pb2'
  # @@protoc_insertion_point(class_scope:electrum.GetMerkleProof)
  })
_sym_db.RegisterMessage(GetMerkleProof)

MerkleProof = _reflection.GeneratedProtocolMessageType('MerkleProof', (_message.Message,), {
  'DESCRIPTOR' : _MERKLEPROOF,
  '__module__' : 'electrum_pb2'
  # @@protoc_insertion_point(class_scope:electrum.MerkleProof)
  })
_sym_db.RegisterMessage(MerkleProof)


# @@protoc_insertion_point(module_scope)
